### ISSUE TITLE
ValueError: Expected values for field: [issue, issn, citations, documents]

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/analytics#114]
```
2/8/2018 3:27:01 PM[2018-02-08 17:27:01 +0000] [3351] [ERROR] Error handling request /ajx/publication/size
2/8/2018 3:27:01 PMTraceback (most recent call last):
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/tweens.py", line 12, in _error_handler
2/8/2018 3:27:01 PM    response = request.invoke_exception_view(exc_info)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/view.py", line 756, in invoke_exception_view
2/8/2018 3:27:01 PM    raise HTTPNotFound
2/8/2018 3:27:01 PMpyramid.httpexceptions.HTTPNotFound: The resource could not be found.
2/8/2018 3:27:01 PM
2/8/2018 3:27:01 PMDuring handling of the above exception, another exception occurred:
2/8/2018 3:27:01 PM
2/8/2018 3:27:01 PMTraceback (most recent call last):
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
2/8/2018 3:27:01 PM    self.handle_request(listener, req, client, addr)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
2/8/2018 3:27:01 PM    respiter = self.wsgi(environ, resp.start_response)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/router.py", line 270, in __call__
2/8/2018 3:27:01 PM    response = self.execution_policy(environ, self)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/router.py", line 278, in default_execution_policy
2/8/2018 3:27:01 PM    return request.invoke_exception_view(reraise=True)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/view.py", line 755, in invoke_exception_view
2/8/2018 3:27:01 PM    reraise_(*exc_info)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/compat.py", line 148, in reraise
2/8/2018 3:27:01 PM    raise value
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/router.py", line 276, in default_execution_policy
2/8/2018 3:27:01 PM    return router.invoke_request(request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/router.py", line 249, in invoke_request
2/8/2018 3:27:01 PM    response = handle_request(request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/tweens.py", line 41, in excview_tween
2/8/2018 3:27:01 PM    response = _error_handler(request, exc)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/tweens.py", line 16, in _error_handler
2/8/2018 3:27:01 PM    reraise(*exc_info)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/compat.py", line 148, in reraise
2/8/2018 3:27:01 PM    raise value
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/tweens.py", line 39, in excview_tween
2/8/2018 3:27:01 PM    response = handler(request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/router.py", line 156, in handle_request
2/8/2018 3:27:01 PM    view_name
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/view.py", line 642, in _call_view
2/8/2018 3:27:01 PM    response = view_callable(context, request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/viewderivers.py", line 390, in attr_view
2/8/2018 3:27:01 PM    return view(context, request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/viewderivers.py", line 368, in predicate_wrapper
2/8/2018 3:27:01 PM    return view(context, request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/viewderivers.py", line 439, in rendered_view
2/8/2018 3:27:01 PM    result = view(context, request)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/pyramid-1.9.1-py3.5.egg/pyramid/viewderivers.py", line 148, in _requestonly_view
2/8/2018 3:27:01 PM    response = view(request)
2/8/2018 3:27:01 PM  File "/app/analytics/control_manager.py", line 115, in check
2/8/2018 3:27:01 PM    return wrapped(request, *arg, **kwargs)
2/8/2018 3:27:01 PM  File "/app/analytics/control_manager.py", line 205, in wrapper
2/8/2018 3:27:01 PM    return wrapped(request, *arg, **kwargs)
2/8/2018 3:27:01 PM  File "/app/analytics/views_ajax.py", line 363, in publication_size
2/8/2018 3:27:01 PM    data = request.stats.publication.collection_size(data['selected_code'], data['selected_collection_code'], field, data['py_range'], data['sa_scope'], data['la_scope'])
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/cache/region.py", line 1231, in decorate
2/8/2018 3:27:01 PM    should_cache_fn)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/cache/region.py", line 833, in get_or_create
2/8/2018 3:27:01 PM    async_creator) as value:
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/lock.py", line 154, in __enter__
2/8/2018 3:27:01 PM    return self._enter()
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/lock.py", line 94, in _enter
2/8/2018 3:27:01 PM    generated = self._enter_create(createdtime)
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/lock.py", line 145, in _enter_create
2/8/2018 3:27:01 PM    created = self.creator()
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/cache/region.py", line 800, in gen_value
2/8/2018 3:27:01 PM    created_value = creator()
2/8/2018 3:27:01 PM  File "/usr/local/lib/python3.5/site-packages/dogpile.cache-0.6.4-py3.5.egg/dogpile/cache/region.py", line 1227, in creator
2/8/2018 3:27:01 PM    return fn(*arg, **kw)
2/8/2018 3:27:01 PM  File "/app/analytics/controller.py", line 1465, in collection_size
2/8/2018 3:27:01 PM    raise ValueError('Expected values for field: [issue, issn, citations, documents]')
2/8/2018 3:27:01 PMValueError: Expected values for field: [issue, issn, citations, documents]
```

**Comment by gustavofonseca** [comment]
Alarme falso.
